# Generated by Django 3.2.4 on 2021-06-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='subscriptions.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('recipient_email', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='subscriptions.customer')),
            ],
        ),
    ]
